project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"


website:
  title: "Lucerne Medical AI Lab"
  site-url: "https://baumgach.github.io/med-AI-website"
  repo-url: "https://github.com/baumgach/med-AI-website"
  favicon: images/favicon.png
  description: "Research group at the University of Lucerne working on interpretable and uncertainty-aware AI for medical imaging and healthcare."
  google-analytics: "G-RYHMRSLGSM"

  back-to-top-navigation: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/baumgach/med-AI-website
  
  navbar:
    search: true
    title: false
    logo: images/logo.png 
    background: "#F6F5F3"
    logo-alt: "Medical AI Group"
    left:
      - href: about/index.qmd
        text: about
      - href: people/index.qmd
        text: people
      - href: research/index.qmd
        text: research
      - href: publications/index.qmd
      - href: jobs/index.qmd
      - href: teaching/index.qmd
      - href: news/index.qmd
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



